### ISSUE TITLE
API requests fail in Safari

### ISSUE THREAD

**Issue by sman591** [ghmeier/my-mlh-dashboard#1]
Not sure what this means, but when it calls the MLH api, this is the error Safari reports back:

> Failed to load resource: Cannot make any requests from null.

Works fine in Chrome, though!

![screenshot 2016-02-10 14 33 39](https://cloud.githubusercontent.com/assets/1441807/12959180/54d6d7ba-d003-11e5-9624-740168e8a4ef.png)

**Comment by ghmeier** [comment]
Hmm, like it has something to do with Safari not accepting the header: "Access-Control-Allow-Origin:null"

I updated a part of the mlh request that might fix it. Let me know if it works now.

**Comment by sman591** [comment]
That fixes it!

**Comment by ghmeier** [comment]
Solid! :+1:
